branches:
  except:
    - gh-pages
language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
before_install:
  - sudo apt-get -y update
  - sudo apt-get install -y libgeoip-dev
  #- sudo apt-get install -y geoip-database
  - wget http://geolite.maxmind.com/download/geoip/database/GeoLiteCountry/GeoIP.dat.gz
  - gunzip GeoIP.dat.gz
  - sudo mkdir -p /usr/local/var/GeoIP/
  - sudo mv GeoIP.dat /usr/local/var/GeoIP/
  - sudo ls -l /usr/
  - sudo ls -l /usr/local/
  - sudo ls -l /usr/local/var/
  - sudo ls -l /usr/local/var/GeoIP/
after_failure:
  - perl report.pl
